import type { Board, Class, Student, Assignment, GradeEntry } from "@/lib/types"

// Mock Classes
export const mockClasses: Class[] = [
  {
    id: "class-1",
    name: "Physics 101",
    subject: "Science",
    grade: "11th Grade",
    period: "1st Period",
    room: "Room 301",
    studentCount: 28,
    startTime: "8:00 AM",
    endTime: "9:30 AM",
    days: ["Monday", "Wednesday", "Friday"],
    color: "bg-blue-500",
    description: "Introduction to Physics concepts including mechanics, thermodynamics, and waves.",
    teacherId: "teacher-1",
  },
  {
    id: "class-2",
    name: "Algebra II",
    subject: "Mathematics",
    grade: "10th Grade",
    period: "2nd Period",
    room: "Room 205",
    studentCount: 24,
    startTime: "9:45 AM",
    endTime: "11:15 AM",
    days: ["Monday", "Wednesday", "Friday"],
    color: "bg-green-500",
    description: "Advanced algebra concepts including functions, equations, and data analysis.",
    teacherId: "teacher-1",
  },
  {
    id: "class-3",
    name: "Chemistry",
    subject: "Science",
    grade: "11th Grade",
    period: "3rd Period",
    room: "Room 302",
    studentCount: 26,
    startTime: "11:30 AM",
    endTime: "1:00 PM",
    days: ["Monday", "Wednesday", "Friday"],
    color: "bg-purple-500",
    description: "Study of matter, its properties, and the changes it undergoes.",
    teacherId: "teacher-1",
  },
  {
    id: "class-4",
    name: "English Literature",
    subject: "English",
    grade: "10th Grade",
    period: "4th Period",
    room: "Room 110",
    studentCount: 22,
    startTime: "1:30 PM",
    endTime: "3:00 PM",
    days: ["Monday", "Wednesday", "Friday"],
    color: "bg-yellow-500",
    description: "Analysis of classic and contemporary literature with focus on critical thinking.",
    teacherId: "teacher-1",
  },
  {
    id: "class-5",
    name: "World History",
    subject: "History",
    grade: "9th Grade",
    period: "5th Period",
    room: "Room 120",
    studentCount: 30,
    startTime: "8:00 AM",
    endTime: "9:30 AM",
    days: ["Tuesday", "Thursday"],
    color: "bg-red-500",
    description: "Survey of world history from ancient civilizations to modern times.",
    teacherId: "teacher-1",
  },
  {
    id: "class-6",
    name: "Computer Science",
    subject: "Technology",
    grade: "12th Grade",
    period: "6th Period",
    room: "Room 405",
    studentCount: 20,
    startTime: "9:45 AM",
    endTime: "11:15 AM",
    days: ["Tuesday", "Thursday"],
    color: "bg-indigo-500",
    description: "Introduction to programming concepts, algorithms, and data structures.",
    teacherId: "teacher-1",
  },
]

// Mock Students
export const mockStudents: Student[] = [
  { id: "1", name: "Alex Johnson", email: "alex@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "2", name: "Jamie Smith", email: "jamie@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
  { id: "3", name: "Taylor Brown", email: "taylor@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "4", name: "Morgan Lee", email: "morgan@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
  { id: "5", name: "Casey Wilson", email: "casey@example.edu", grade: "9th", classes: ["class-5"] },
  { id: "6", name: "Jordan Miller", email: "jordan@example.edu", grade: "12th", classes: ["class-6"] },
  { id: "7", name: "Riley Davis", email: "riley@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "8", name: "Quinn Moore", email: "quinn@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
  { id: "9", name: "Avery Thompson", email: "avery@example.edu", grade: "9th", classes: ["class-5"] },
  { id: "10", name: "Cameron Garcia", email: "cameron@example.edu", grade: "12th", classes: ["class-6"] },
  { id: "11", name: "Reese Martinez", email: "reese@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "12", name: "Skyler Robinson", email: "skyler@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
  { id: "13", name: "Finley Clark", email: "finley@example.edu", grade: "9th", classes: ["class-5"] },
  { id: "14", name: "Drew Rodriguez", email: "drew@example.edu", grade: "12th", classes: ["class-6"] },
  { id: "15", name: "Blake Lewis", email: "blake@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "16", name: "Parker Lee", email: "parker@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
  { id: "17", name: "Dakota Walker", email: "dakota@example.edu", grade: "9th", classes: ["class-5"] },
  { id: "18", name: "Hayden Hall", email: "hayden@example.edu", grade: "12th", classes: ["class-6"] },
  { id: "19", name: "Rowan Young", email: "rowan@example.edu", grade: "11th", classes: ["class-1", "class-3"] },
  { id: "20", name: "Charlie King", email: "charlie@example.edu", grade: "10th", classes: ["class-2", "class-4"] },
]

// Mock Assignments
export const mockAssignments: Assignment[] = [
  {
    id: "assignment-1",
    title: "Newton's Laws Lab Report",
    description: "Write a lab report on the experiments demonstrating Newton's three laws of motion.",
    classId: "class-1",
    className: "Physics 101",
    dueDate: new Date("2025-04-15"),
    points: 100,
    type: "Lab Report",
    status: "active",
    attachments: [
      { id: "att-1", name: "Lab_Instructions.pdf", url: "#", type: "pdf", size: "1.2 MB" },
      { id: "att-2", name: "Data_Collection_Template.xlsx", url: "#", type: "xlsx", size: "0.5 MB" },
    ],
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "assignment-2",
    title: "Quadratic Equations Problem Set",
    description: "Complete problems 1-20 on quadratic equations and their applications.",
    classId: "class-2",
    className: "Algebra II",
    dueDate: new Date("2025-04-12"),
    points: 50,
    type: "Homework",
    status: "active",
    attachments: [{ id: "att-3", name: "Quadratic_Problems.pdf", url: "#", type: "pdf", size: "0.8 MB" }],
    createdAt: new Date("2025-04-05"),
  },
  {
    id: "assignment-3",
    title: "Periodic Table Quiz",
    description: "Quiz covering the periodic table of elements, their properties, and trends.",
    classId: "class-3",
    className: "Chemistry",
    dueDate: new Date("2025-04-10"),
    points: 25,
    type: "Quiz",
    status: "active",
    attachments: [],
    createdAt: new Date("2025-04-03"),
  },
  {
    id: "assignment-4",
    title: "Shakespeare Essay",
    description: "Write a 5-page analytical essay on the themes in Shakespeare's Macbeth.",
    classId: "class-4",
    className: "English Literature",
    dueDate: new Date("2025-04-20"),
    points: 100,
    type: "Essay",
    status: "active",
    attachments: [
      { id: "att-4", name: "Essay_Guidelines.pdf", url: "#", type: "pdf", size: "0.7 MB" },
      { id: "att-5", name: "Rubric.pdf", url: "#", type: "pdf", size: "0.3 MB" },
    ],
    createdAt: new Date("2025-04-02"),
  },
  {
    id: "assignment-5",
    title: "Ancient Civilizations Presentation",
    description: "Create and deliver a presentation on an ancient civilization of your choice.",
    classId: "class-5",
    className: "World History",
    dueDate: new Date("2025-04-25"),
    points: 75,
    type: "Presentation",
    status: "active",
    attachments: [{ id: "att-6", name: "Presentation_Requirements.pdf", url: "#", type: "pdf", size: "0.6 MB" }],
    createdAt: new Date("2025-04-04"),
  },
  {
    id: "assignment-6",
    title: "Python Programming Project",
    description: "Develop a Python application that solves a real-world problem.",
    classId: "class-6",
    className: "Computer Science",
    dueDate: new Date("2025-04-30"),
    points: 150,
    type: "Project",
    status: "active",
    attachments: [
      { id: "att-7", name: "Project_Specifications.pdf", url: "#", type: "pdf", size: "1.0 MB" },
      { id: "att-8", name: "Sample_Code.py", url: "#", type: "py", size: "0.2 MB" },
    ],
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "assignment-7",
    title: "Thermodynamics Test",
    description: "Comprehensive test covering thermodynamics principles and applications.",
    classId: "class-1",
    className: "Physics 101",
    dueDate: new Date("2025-04-18"),
    points: 100,
    type: "Test",
    status: "active",
    attachments: [{ id: "att-9", name: "Study_Guide.pdf", url: "#", type: "pdf", size: "1.5 MB" }],
    createdAt: new Date("2025-04-05"),
  },
  {
    id: "assignment-8",
    title: "Logarithms Worksheet",
    description: "Complete the worksheet on logarithmic functions and their properties.",
    classId: "class-2",
    className: "Algebra II",
    dueDate: new Date("2025-04-14"),
    points: 30,
    type: "Worksheet",
    status: "active",
    attachments: [{ id: "att-10", name: "Logarithms_Worksheet.pdf", url: "#", type: "pdf", size: "0.5 MB" }],
    createdAt: new Date("2025-04-07"),
  },
]

// Mock Grades
export const mockGrades: GradeEntry[] = [
  {
    id: "grade-1",
    studentId: "1",
    studentName: "Alex Johnson",
    assignmentId: "assignment-1",
    assignmentTitle: "Newton's Laws Lab Report",
    classId: "class-1",
    className: "Physics 101",
    score: 92,
    possiblePoints: 100,
    feedback: "Excellent analysis of Newton's laws. Your experimental design was well thought out.",
    submittedAt: new Date("2025-04-14"),
    gradedAt: new Date("2025-04-16"),
  },
  {
    id: "grade-2",
    studentId: "2",
    studentName: "Jamie Smith",
    assignmentId: "assignment-2",
    assignmentTitle: "Quadratic Equations Problem Set",
    classId: "class-2",
    className: "Algebra II",
    score: 45,
    possiblePoints: 50,
    feedback: "Great work! Just a small error on problem 15.",
    submittedAt: new Date("2025-04-11"),
    gradedAt: new Date("2025-04-13"),
  },
  {
    id: "grade-3",
    studentId: "3",
    studentName: "Taylor Brown",
    assignmentId: "assignment-1",
    assignmentTitle: "Newton's Laws Lab Report",
    classId: "class-1",
    className: "Physics 101",
    score: 85,
    possiblePoints: 100,
    feedback: "Good work overall. Your conclusion could use more depth in analyzing the results.",
    submittedAt: new Date("2025-04-14"),
    gradedAt: new Date("2025-04-16"),
  },
  {
    id: "grade-4",
    studentId: "4",
    studentName: "Morgan Lee",
    assignmentId: "assignment-2",
    assignmentTitle: "Quadratic Equations Problem Set",
    classId: "class-2",
    className: "Algebra II",
    score: 48,
    possiblePoints: 50,
    feedback: "Excellent work! Very thorough solutions.",
    submittedAt: new Date("2025-04-11"),
    gradedAt: new Date("2025-04-13"),
  },
  {
    id: "grade-5",
    studentId: "5",
    studentName: "Casey Wilson",
    assignmentId: "assignment-5",
    assignmentTitle: "Ancient Civilizations Presentation",
    classId: "class-5",
    className: "World History",
    score: 70,
    possiblePoints: 75,
    feedback: "Great presentation on Ancient Egypt. Your visual aids were particularly effective.",
    submittedAt: new Date("2025-04-24"),
    gradedAt: new Date("2025-04-26"),
  },
]

// Mock Boards
export const mockTeacherBoards: Board[] = [
  {
    id: "board-1",
    title: "Physics 101 - Spring Semester",
    description: "Track assignments and projects for Physics 101",
    createdAt: new Date("2025-01-15"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: true,
    color: "bg-green-500",
  },
  {
    id: "board-2",
    title: "Algebra II - Unit 5",
    description: "Organize tasks for Algebra II Unit 5: Quadratic Functions",
    createdAt: new Date("2025-02-10"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: true,
    color: "bg-blue-500",
  },
  {
    id: "board-3",
    title: "Chemistry Lab Schedule",
    description: "Manage chemistry lab activities and materials",
    createdAt: new Date("2025-02-20"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: false,
    color: "bg-purple-500",
  },
  {
    id: "board-4",
    title: "English Literature Essay Topics",
    description: "Track essay assignments and grading progress",
    createdAt: new Date("2025-03-05"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: true,
    color: "bg-yellow-500",
  },
  {
    id: "board-5",
    title: "World History Project Ideas",
    description: "Brainstorm and organize project ideas for World History",
    createdAt: new Date("2025-03-15"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: false,
    color: "bg-red-500",
  },
  {
    id: "board-6",
    title: "Computer Science Curriculum Planning",
    description: "Plan and organize Computer Science curriculum",
    createdAt: new Date("2025-03-25"),
    ownerId: "teacher-1",
    ownerName: "Dr. Smith",
    shared: false,
    color: "bg-indigo-500",
  },
]

// Mock Calendar Events
export const mockCalendarEvents = [
  {
    id: "event-1",
    title: "Physics 101 Class",
    start: new Date("2025-04-10T08:00:00"),
    end: new Date("2025-04-10T09:30:00"),
    classId: "class-1",
    color: "bg-blue-500",
    type: "class",
  },
  {
    id: "event-2",
    title: "Algebra II Class",
    start: new Date("2025-04-10T09:45:00"),
    end: new Date("2025-04-10T11:15:00"),
    classId: "class-2",
    color: "bg-green-500",
    type: "class",
  },
  {
    id: "event-3",
    title: "Chemistry Class",
    start: new Date("2025-04-10T11:30:00"),
    end: new Date("2025-04-10T13:00:00"),
    classId: "class-3",
    color: "bg-purple-500",
    type: "class",
  },
  {
    id: "event-4",
    title: "English Literature Class",
    start: new Date("2025-04-10T13:30:00"),
    end: new Date("2025-04-10T15:00:00"),
    classId: "class-4",
    color: "bg-yellow-500",
    type: "class",
  },
  {
    id: "event-5",
    title: "Department Meeting",
    start: new Date("2025-04-11T15:30:00"),
    end: new Date("2025-04-11T16:30:00"),
    color: "bg-gray-500",
    type: "meeting",
  },
  {
    id: "event-6",
    title: "Parent-Teacher Conferences",
    start: new Date("2025-04-12T13:00:00"),
    end: new Date("2025-04-12T18:00:00"),
    color: "bg-red-500",
    type: "meeting",
  },
  {
    id: "event-7",
    title: "Physics Lab Setup",
    start: new Date("2025-04-13T07:00:00"),
    end: new Date("2025-04-13T08:00:00"),
    classId: "class-1",
    color: "bg-blue-500",
    type: "preparation",
  },
  {
    id: "event-8",
    title: "Grade Algebra Assignments",
    start: new Date("2025-04-14T16:00:00"),
    end: new Date("2025-04-14T18:00:00"),
    classId: "class-2",
    color: "bg-green-500",
    type: "grading",
  },
]

// Mock Analytics Data
export const mockAnalyticsData = {
  classPerformance: [
    { class: "Physics 101", averageGrade: 87, assignmentsCompleted: 92, participationRate: 95 },
    { class: "Algebra II", averageGrade: 82, assignmentsCompleted: 88, participationRate: 90 },
    { class: "Chemistry", averageGrade: 79, assignmentsCompleted: 85, participationRate: 88 },
    { class: "English Literature", averageGrade: 85, assignmentsCompleted: 90, participationRate: 92 },
    { class: "World History", averageGrade: 81, assignmentsCompleted: 87, participationRate: 89 },
    { class: "Computer Science", averageGrade: 90, assignmentsCompleted: 94, participationRate: 96 },
  ],
  studentProgress: [
    { month: "January", averageGrade: 78 },
    { month: "February", averageGrade: 80 },
    { month: "March", averageGrade: 83 },
    { month: "April", averageGrade: 85 },
  ],
  assignmentCompletion: [
    { type: "Homework", completed: 94, late: 4, missing: 2 },
    { type: "Quiz", completed: 98, late: 1, missing: 1 },
    { type: "Test", completed: 96, late: 2, missing: 2 },
    { type: "Project", completed: 90, late: 7, missing: 3 },
    { type: "Essay", completed: 88, late: 8, missing: 4 },
    { type: "Lab Report", completed: 92, late: 5, missing: 3 },
  ],
  gradeDistribution: [
    { grade: "A", count: 35 },
    { grade: "B", count: 42 },
    { grade: "C", count: 18 },
    { grade: "D", count: 4 },
    { grade: "F", count: 1 },
  ],
}

// Mock Notifications
export const mockNotifications = [
  {
    id: "notif-1",
    title: "Assignment Submitted",
    message: "Alex Johnson submitted Newton's Laws Lab Report",
    timestamp: new Date("2025-04-14T14:32:00"),
    read: false,
    type: "submission",
    link: "/assignments/grade/assignment-1",
  },
  {
    id: "notif-2",
    title: "Question Asked",
    message: "Jamie Smith asked a question about the Quadratic Equations Problem Set",
    timestamp: new Date("2025-04-13T10:15:00"),
    read: true,
    type: "question",
    link: "/classes/class-2/discussion",
  },
  {
    id: "notif-3",
    title: "Reminder",
    message: "Parent-Teacher Conferences scheduled for tomorrow",
    timestamp: new Date("2025-04-11T09:00:00"),
    read: false,
    type: "reminder",
    link: "/calendar",
  },
  {
    id: "notif-4",
    title: "New Announcement",
    message: "Principal Johnson posted a new announcement",
    timestamp: new Date("2025-04-10T15:45:00"),
    read: true,
    type: "announcement",
    link: "/announcements",
  },
  {
    id: "notif-5",
    title: "Grade Appeal",
    message: "Morgan Lee submitted a grade appeal for Quadratic Equations Problem Set",
    timestamp: new Date("2025-04-13T16:20:00"),
    read: false,
    type: "appeal",
    link: "/grades/appeals",
  },
]

// Mock Resources
export const mockResources = [
  {
    id: "resource-1",
    title: "Physics Curriculum Guide",
    description: "Comprehensive curriculum guide for Physics 101",
    type: "document",
    url: "#",
    fileType: "pdf",
    fileSize: "2.5 MB",
    uploadedAt: new Date("2025-01-10"),
    tags: ["physics", "curriculum", "guide"],
  },
  {
    id: "resource-2",
    title: "Algebra II Lesson Plans",
    description: "Collection of lesson plans for Algebra II",
    type: "document",
    url: "#",
    fileType: "docx",
    fileSize: "1.8 MB",
    uploadedAt: new Date("2025-01-15"),
    tags: ["algebra", "lesson plans", "mathematics"],
  },
  {
    id: "resource-3",
    title: "Chemistry Lab Safety Guidelines",
    description: "Safety guidelines for chemistry laboratory activities",
    type: "document",
    url: "#",
    fileType: "pdf",
    fileSize: "1.2 MB",
    uploadedAt: new Date("2025-01-20"),
    tags: ["chemistry", "lab safety", "guidelines"],
  },
  {
    id: "resource-4",
    title: "English Literature Reading List",
    description: "Required and recommended reading for English Literature",
    type: "document",
    url: "#",
    fileType: "pdf",
    fileSize: "0.8 MB",
    uploadedAt: new Date("2025-01-25"),
    tags: ["english", "literature", "reading list"],
  },
  {
    id: "resource-5",
    title: "World History Timeline Template",
    description: "Template for creating historical timelines",
    type: "template",
    url: "#",
    fileType: "pptx",
    fileSize: "3.2 MB",
    uploadedAt: new Date("2025-02-01"),
    tags: ["history", "timeline", "template"],
  },
  {
    id: "resource-6",
    title: "Computer Science Project Rubric",
    description: "Evaluation rubric for computer science projects",
    type: "document",
    url: "#",
    fileType: "pdf",
    fileSize: "0.5 MB",
    uploadedAt: new Date("2025-02-05"),
    tags: ["computer science", "rubric", "evaluation"],
  },
  {
    id: "resource-7",
    title: "Physics Simulation Software",
    description: "Interactive physics simulation software for classroom demonstrations",
    type: "software",
    url: "#",
    fileType: "exe",
    fileSize: "45 MB",
    uploadedAt: new Date("2025-02-10"),
    tags: ["physics", "simulation", "software"],
  },
  {
    id: "resource-8",
    title: "Algebra II Practice Problems",
    description: "Collection of practice problems for Algebra II",
    type: "document",
    url: "#",
    fileType: "pdf",
    fileSize: "1.5 MB",
    uploadedAt: new Date("2025-02-15"),
    tags: ["algebra", "practice problems", "mathematics"],
  },
]
